version: "3"

services:
  picvid-nginx:
    image: nginx:1.13-alpine
    container_name: picvid-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./htdocs:/htdocs:rw
      - ./img-data:/htdocs/data/images:rw
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - picvid-net
    depends_on:
      - picvid-php
      - picvid-mysql

  picvid-php:
    build:
      context: ./picvid-nginx
    container_name: picvid-php
    restart: always
    volumes:
      - ./htdocs:/htdocs:rw
      - ./img-data:/htdocs/data/images:rw
      - ./config/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - picvid-net

  picvid-mysql:
    image: mysql:5.7
    container_name: picvid-mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: picvid-demo
      MYSQL_USER: picvid
      MYSQL_PASSWORD: qnpsq8w7jQy5HuWCKsMK
    networks:
      - picvid-net

networks:
  picvid-net:
    driver: bridge