version: "3"

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/www
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php-picvid:latest
    volumes:
      - ./www:/www
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: A4LCscV_P8GMdrG
      MYSQL_DATABASE: picvid-demo
      MYSQL_USER: picvid
      MYSQL_PASSWORD: qnpsq8w7jQy5HuWCKsMK
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: